alertmanager:
  enabled: false

pushgateway:
  enabled: false

server:
  service:
    type: NodePort
    nodePort: 30090  # You can access Prometheus UI on http://localhost:30090
  resources:
    requests:
      memory: 512Mi
      cpu: 250m
    limits:
      memory: 1Gi
      cpu: 500m

additionalScrapeConfigs:
  - job_name: 'garmin-scaler'
    metrics_path: /prometheus
    static_configs:
      - targets: ['garmin-scaler-service.default.svc.cluster.local:8080']

replicaCount: 1

image:
  repository: garmin-scaler
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8080
  targetPort: 8080
  nodePort: 30080 # Optional: Specify a NodePort if using NodePort service type

keda:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  pollingInterval: 30 # seconds
  cooldownPeriod: 300 # seconds
  prometheus:
    serverAddress: http://prometheus-server.default.svc.cluster.local:9090
    query: sum(rate(garmin_uploads_total{job="garmin-scaler"}[2m]))
    threshold: "5" # Target 5 uploads/second across all pods to trigger scaling
