apiVersion: apps/v1
kind: Deployment
metadata:
  name: garmin-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: garmin-app
  template:
    metadata:
      labels:
        app: garmin-app
    spec:
      containers:
        - name: garmin-app
          image: garmin-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          env:
            - name: MICRONAUT_ENVIRONMENTS
              value: "k8s"
