replicaCount: 1

image:
  repository: betulince220/garmin-scaler-runtime
  pullPolicy: IfNotPresent
  tag: latest

service:
  type: ClusterIP
  port: 8080

resources: {}

prometheus:
  alertmanager:
    enabled: false

  kube-state-metrics:
    enabled: false

  prometheus-node-exporter:
    enabled: false

  prometheus-pushgateway:
    enabled: false

  scrapePath: /prometheus
  scrapePort: 8080

keda:
  minReplicaCount: 1
  maxReplicaCount: 5
  metricName: activities_uploaded_gauge
  threshold: 3
  pollingInterval: 15
  cooldownPeriod: 30
